// Code generated by "stringer -type=JobState -linecomment -trimprefix Job -output job_state.go"; DO NOT EDIT.

package sqlq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInvalid-0]
	_ = x[StatePending-1]
	_ = x[StateRunning-2]
	_ = x[StateSuccess-3]
	_ = x[StateErrored-4]
	_ = x[StateCancelling-5]
	_ = x[StateCancelled-6]
}

const _JobState_name = "invalidpendingrunningsuccesserroredcancellingcancelled"

var _JobState_index = [...]uint8{0, 7, 14, 21, 28, 35, 45, 54}

func (i JobState) String() string {
	if i >= JobState(len(_JobState_index)-1) {
		return "JobState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobState_name[_JobState_index[i]:_JobState_index[i+1]]
}
