name: Golang CI
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: Golang CI
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source
        uses: actions/checkout@v3

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./... -postgres-url postgres://postgres:password@localhost:5432 -v
